import { Request, Response } from "express";
const admin = require("../config/firebaseInitialization");

const firestore = admin.firestore();

interface AIConversation {
  id: string;
  prompt: string;
  answer: string;
}

interface AllStories {
  story: string;
  created_at: string;
}

const formatDate = (date: Date): string => {
  const options: Intl.DateTimeFormatOptions = {
    day: "2-digit",
    month: "long",
    year: "numeric",
  };
  return date.toLocaleDateString("en-GB", options);
};

export const newStoryController = async (req: Request, res: Response) => {
  const { story_name } = req.body;
  const user_uid = req.user?.uid;

  try {
    const userDocRef = admin.firestore().collection("Users").doc(user_uid);

    // Add a new story to the user's stories subcollection
    const newStoryRef = await userDocRef.collection("Stories").add({
      story_name: story_name,
      created_at: admin.firestore.FieldValue.serverTimestamp(),
    });

    // Retrieve the story ID generated by Firestore
    const storyId = newStoryRef.id;

    res.status(201).json({ story_id: storyId });
  } catch (error) {
    console.error("Error creating new story:", error);
    res.status(500).json({ error: "Failed to create new Story " });
  }
};

export const getAIConversationsController = async (
  req: Request,
  res: Response
) => {
  const { story_id } = req.params;
  const user_uid = req.user?.uid;

  if (!story_id) {
    return res
      .status(400)
      .json({ error: "Story ID is missing in the request body" });
  }

  try {
    const conversationsRef = admin
      .firestore()
      .collection("Users")
      .doc(user_uid)
      .collection("Stories")
      .doc(story_id)
      .collection("AI_Conversation");

    const conversationsSnapshot = await conversationsRef.get();

    const conversationsData: AIConversation[] = conversationsSnapshot.docs.map(
      (doc: any) =>
        ({
          id: doc.id,
          ...doc.data(),
        } as AIConversation)
    );

    return res.status(200).json({ conversations: conversationsData });
  } catch (error) {
    console.error("Error retrieving AI conversations:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
};

export const validateStoryIdController = async (
  req: Request,
  res: Response
) => {
  try {
    const { story_id } = req.body;
    const user_uid = req.user?.uid;

    if (!story_id) {
      return res
        .status(400)
        .json({ error: "Story ID is missing in the request parameters" });
    }

    // Reference to the user's stories collection
    const storiesCollection = admin
      .firestore()
      .collection("Users")
      .doc(user_uid)
      .collection("Stories");

    // Check if the story with the provided ID exists
    const storyDoc = await storiesCollection.doc(story_id).get();

    if (storyDoc.exists) {
      const story_name = storyDoc.data().story_name;
      return res.status(200).json({ exists: true, story_name});
    } else {
      return res
        .status(404)
        .json({ exists: false, message: "Story not found" });
    }
  } catch (error) {
    console.error("Error in validating story:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
};

export const getAllStoriesController = async (req: Request, res: Response) => {
  try {
    const user_uid = req.user?.uid;

    const storiesCollectionRef = admin
      .firestore()
      .collection("Users")
      .doc(user_uid)
      .collection("Stories");

    const storiesSnapshot = await storiesCollectionRef.get();
    const storiesData: AllStories[] = storiesSnapshot.docs.map((doc: any) => {
      const createdAt = doc.data().created_at.toDate();
      const formattedDate = formatDate(createdAt);
      return {
        id: doc.id,
        ...doc.data(),
        created_at: formattedDate,
      } as AllStories;
    });

    return res.status(200).json({ all_stories: storiesData });
  } catch (error) {
    console.error("Error getting all stories:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
};

export const saveEditorContentController = async (
  req: Request,
  res: Response
) => {
  try {
    const user_uid = req.user?.uid;
    const { editor_content } = req.body;
    const { story_id } = req.params;

    if (editor_content === "") {
      return res.status(400).json({ error: "Please provide editor content" });
    }

    console.log("editor_content: ", editor_content);

    const storyDocRef = admin
      .firestore()
      .collection("Users")
      .doc(user_uid)
      .collection("Stories")
      .doc(story_id);

    await storyDocRef.set(
      {
        editor_content: editor_content,
      },
      { merge: true }
    );

    res.status(200).json({ message: "Editor content saved successfully" });
  } catch (error) {
    console.error("Error saving editor content:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
};

export const getEditorContentController = async (req: Request, res: Response) => {
  try {
    const user_uid = req.user?.uid;
    const { story_id } = req.params;

    const storyDocRef = admin
      .firestore()
      .collection("Users")
      .doc(user_uid)
      .collection("Stories")
      .doc(story_id);

    const storyDoc = await storyDocRef.get();

    if (!storyDoc.exists) {
      return res.status(404).json({ error: "Story not found" });
    }

    const data = storyDoc.data();
    res.status(200).json({ editor_content: data.editor_content });
  } catch (error) {
    console.error("Error getting editor content:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
};
