import { Request, Response } from "express";
const admin = require("../config/firebaseInitialization");

const firestore = admin.firestore();

export const newStoryController = async (req: Request, res: Response) => {
  const { story_name } = req.body;
  const user_uid = req.user?.uid;

  try {
    const userDocRef = admin.firestore().collection("Users").doc(user_uid);

    // Add a new story to the user's stories subcollection
    const newStoryRef = await userDocRef.collection("Stories").add({
      story_name: story_name,
      created_at: admin.firestore.FieldValue.serverTimestamp(),
    });

    // Retrieve the story ID generated by Firestore
    const storyId = newStoryRef.id;

    res.status(201).json({ story_id: storyId });
  } catch (error) {
    console.error("Error creating new story:", error);
    res.status(500).json({ error: "Failed to create new Story " });
  }
};
